# Generated by Django 2.0.13 on 2019-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterName', models.CharField(max_length=25)),
                ('procurementEntityId', models.CharField(max_length=20)),
                ('procurementEntityRegion', models.CharField(max_length=25)),
                ('deliveryRegion', models.CharField(max_length=25)),
                ('valueLowLimit', models.IntegerField()),
                ('valueHighLimit', models.IntegerField()),
                ('procurementType', models.CharField(max_length=20)),
                ('cpv', models.CharField(max_length=20)),
                ('deliveryDateLowLimit', models.DateField(blank=True, null=True)),
                ('deliveryDateHighLimit', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
