# Generated by Django 2.0.13 on 2019-07-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='username',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
    ]
