# Generated by Django 2.0.13 on 2019-07-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_filter_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='username',
            new_name='user',
        ),
    ]
