# Generated by Django 2.0.13 on 2019-07-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190707_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='deliveryDateHighLimit',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='deliveryDateLowLimit',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='procurementEntityRegion',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='procurementType',
        ),
    ]
